// This file is autogenerated by VESC Tool

#ifndef CONF_DEFAULT_H_
#define CONF_DEFAULT_H_

// CAN ID
#ifndef CONF_CONTROLLER_ID
#define CONF_CONTROLLER_ID 104
#endif

// CAN Status Rate
#ifndef CONF_SEND_CAN_STATUS_RATE_HZ
#define CONF_SEND_CAN_STATUS_RATE_HZ 10
#endif

// CAN Baud Rate
#ifndef CONF_CAN_BAUD_RATE
#define CONF_CAN_BAUD_RATE 2
#endif

// Temp Limit Start
#ifndef CONF_TEMP_LIM_START
#define CONF_TEMP_LIM_START 60
#endif

// Temp Limit End
#ifndef CONF_TEMP_LIM_END
#define CONF_TEMP_LIM_END 70
#endif

// Voltage Limit Start
#ifndef CONF_VOLT_LOWER_LIM_START
#define CONF_VOLT_LOWER_LIM_START 20
#endif

// Voltage Limit End
#ifndef CONF_VOLT_LOWER_LIM_END
#define CONF_VOLT_LOWER_LIM_END 15
#endif

// Voltage Load Start
#ifndef CONF_LOAD_VOLT_START
#define CONF_LOAD_VOLT_START 40
#endif

// Voltage Load Max
#ifndef CONF_LOAD_VOLT_MAX
#define CONF_LOAD_VOLT_MAX 50
#endif

// Voltage Load Max Fraction
#ifndef CONF_LOAD_VOLT_MAX_FRACTION
#define CONF_LOAD_VOLT_MAX_FRACTION 0
#endif

// CONF_DEFAULT_H_
#endif

