// This file is autogenerated by VESC Tool

#include <string.h>
#include "buffer.h"
#include "conf_general.h"
#include "confparser.h"

int32_t confparser_serialize_main_config_t(uint8_t *buffer, const main_config_t *conf) {
	int32_t ind = 0;

	buffer_append_uint32(buffer, MAIN_CONFIG_T_SIGNATURE, &ind);

	buffer[ind++] = (uint8_t)conf->controller_id;
	buffer_append_uint32(buffer, conf->send_can_status_rate_hz, &ind);
	buffer[ind++] = conf->can_baud_rate;
	buffer_append_float32_auto(buffer, conf->temp_lim_start, &ind);
	buffer_append_float32_auto(buffer, conf->temp_lim_end, &ind);
	buffer_append_float32_auto(buffer, conf->volt_lower_lim_start, &ind);
	buffer_append_float32_auto(buffer, conf->volt_lower_lim_end, &ind);
	buffer_append_float32_auto(buffer, conf->load_volt_start, &ind);
	buffer_append_float32_auto(buffer, conf->load_volt_max, &ind);
	buffer_append_float32_auto(buffer, conf->load_volt_max_fraction, &ind);

	return ind;
}

bool confparser_deserialize_main_config_t(const uint8_t *buffer, main_config_t *conf) {
	int32_t ind = 0;

	uint32_t signature = buffer_get_uint32(buffer, &ind);
	if (signature != MAIN_CONFIG_T_SIGNATURE) {
		return false;
	}

	conf->controller_id = buffer[ind++];
	conf->send_can_status_rate_hz = buffer_get_uint32(buffer, &ind);
	conf->can_baud_rate = buffer[ind++];
	conf->temp_lim_start = buffer_get_float32_auto(buffer, &ind);
	conf->temp_lim_end = buffer_get_float32_auto(buffer, &ind);
	conf->volt_lower_lim_start = buffer_get_float32_auto(buffer, &ind);
	conf->volt_lower_lim_end = buffer_get_float32_auto(buffer, &ind);
	conf->load_volt_start = buffer_get_float32_auto(buffer, &ind);
	conf->load_volt_max = buffer_get_float32_auto(buffer, &ind);
	conf->load_volt_max_fraction = buffer_get_float32_auto(buffer, &ind);

	return true;
}

void confparser_set_defaults_main_config_t(main_config_t *conf) {
	conf->controller_id = HW_DEFAULT_ID;
	conf->send_can_status_rate_hz = CONF_SEND_CAN_STATUS_RATE_HZ;
	conf->can_baud_rate = CONF_CAN_BAUD_RATE;
	conf->temp_lim_start = CONF_TEMP_LIM_START;
	conf->temp_lim_end = CONF_TEMP_LIM_END;
	conf->volt_lower_lim_start = CONF_VOLT_LOWER_LIM_START;
	conf->volt_lower_lim_end = CONF_VOLT_LOWER_LIM_END;
	conf->load_volt_start = CONF_LOAD_VOLT_START;
	conf->load_volt_max = CONF_LOAD_VOLT_MAX;
	conf->load_volt_max_fraction = CONF_LOAD_VOLT_MAX_FRACTION;
}

